Numpy Arrays - Introduction

In [2]:
#This is how lists are
a = [1,3,5,7,23,2]
print(type(a))
print(a)

<class 'list'>
[1, 3, 5, 7, 23, 2]


In [22]:
#every elements maintains its identity
b = [1,3,5, True, (2,5), "nashit", {3,5}]
print(b)
type(b)

[1, 3, 5, True, (2, 5), 'nashit', {3, 5}]


list

In [4]:
import numpy

In [5]:
numpy.__version__

'1.26.0'

In [4]:
#np -> standard

import numpy as np
np.__version__

'1.23.5'

In [11]:
# np.array -> array constructor
arr0 = np.array(5)

In [12]:
print(arr0)

5


In [13]:
type(arr0)

numpy.ndarray

In [14]:
#ndim -> no of dimension
arr0.ndim

0

In [15]:
arr1 = np.array([5, 5, 2, 3.4])

In [18]:
type(arr1)

numpy.ndarray

In [17]:
arr1.ndim

1

In [19]:
print(arr1)

[5.  5.  2.  3.4]


In [60]:
a1 = np.array([3, 6, 4, "vinod", 7, 4, 2])
print(a1)
print(type(a1))
print(a1.ndim)
a1.dtype

['3' '6' '4' 'vinod' '7' '4' '2']
<class 'numpy.ndarray'>
1


dtype('<U11')

In [26]:
arr4 = np.array([5+9j,2,3])
print(arr4)

[5.+9.j 2.+0.j 3.+0.j]


In [29]:
a2 = np.array(['c', 'd', 't', 8])
print(a2)

['c' 'd' 't' '8']


In [30]:
a3 = np.array([9, 4, 0, 6.3, 9, 700])
print(a3)

[  9.    4.    0.    6.3   9.  700. ]


In [37]:
arr2 = np.array([ 
    [8, 2, 8, 5, 1, 0, 5],
    [0, 9, 0, 8, 1, 0, 9] 
])
arr2.ndim

2

In [39]:
arr3 = np.array(
    [
    [9, 8]
]
)
arr2.ndim

2

In [48]:
arr3 = np.array (
    [
        [
            [6,3,4], [4,2,7],[3,2,5],[2,4,5], ['b', 'r', 3]
        ]
    ]
)
arr3.ndim

3

In [2]:
import numpy as np

a = np.array(7)
print(a)
print(type(a))
print(a.ndim)

7
<class 'numpy.ndarray'>
0


In [3]:
b = np.array([5,3,6,8])
print(b)
print(type(b))
print(b.ndim)

[5 3 6 8]
<class 'numpy.ndarray'>
1


In [5]:
my_list = []
c = np.array(my_list)
print(type(my_list))
print(type(c))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
for i in range(1,5):
    x = int(input('elements: '))
    my_list.append(x)
d = np.array(my_list)
print(d)

elements:  7
elements:  6
elements:  9
elements:  3


[7 6 9 3]


In [7]:
type(d)

numpy.ndarray

In [9]:
my_list
type(my_list)

list

In [10]:
e = np.zeros(4)
print(e)

[0. 0. 0. 0.]


In [11]:
f = np.ones(5)
print(f)

[1. 1. 1. 1. 1.]


In [13]:
g = np.arange(8)
print(g)

[0 1 2 3 4 5 6 7]


In [16]:
#np.arange(start, stop, steps, dtype)
h = np.arange(15,25)
h

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
i = np.arange(0,10,4)
i

array([0, 4, 8])

In [24]:
#Spacial
#linespace
#IQR (25%), 75%

j = np.linspace(0,10, num= 6)
j

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [28]:
k = np.random.rand(8)
k
#(0-1)

array([0.77183424, 0.1713954 , 0.38003446, 0.0844904 , 0.01040372,
       0.9500932 , 0.62600577, 0.4305369 ])

In [59]:
#(- -> +)
#array elements
l = np.random.randn(6)
l.dtype


dtype('float64')

In [56]:
m = np.random.ranf(6)
print(m)
print(m.dtype)

[0.66749996 0.74014606 0.50495735 0.04612815 0.48442563 0.1444388 ]
float64


In [55]:
#(start, stop, count)
n = np.random.randint(4, 20, 5)
print(n)
print(n.dtype)

[ 7 17 17 12  8]
int32


In [53]:
#(min, max, count)
o = np.linspace(100, 1000, num=5)
o

array([ 100.,  400.,  700., 1000.])

In [54]:
o.dtype

dtype('float64')

In [65]:
p = np.array(['vino', 'mu', 'ra'])
p.dtype

dtype('<U4')

In [62]:
q = np.array(['a', 'b'])
q.dtype

dtype('<U1')

In [89]:
r = np.array([545456354])
r.dtype

#23e2 = 2.3 *10^3

dtype('int32')

In [70]:
s = np.array([True])
s.dtype

dtype('bool')

In [91]:
t = np.array([0+1j])
t.dtype

dtype('complex128')

In [93]:
v = np.array(['a', 'S', 'w', 'x', 3,5,6,7, False])
v.dtype

dtype('<U11')

In [107]:
w = np.array([2,5,7,8], dtype = np.float_)
print(w)
print(w.dtype)

[2. 5. 7. 8.]
float64


In [109]:
x = np.array([2,5,6,8,9.2], dtype=np.int_)
print(x)
print(x.dtype)

[2 5 6 8 9]
int32


In [110]:
y = np.array([6,3,8,9])
print(y)
print(y.dtype)

[6 3 8 9]
int32


In [115]:
z = np.longfloat(y)
print(z)
print(z.dtype)

[6. 3. 8. 9.]
float64


In [1]:
# List & Arrays -> Datatype 

In [2]:
a = []
type(a)

list

In [6]:
b = [i**2 for i in range(1,15)]
b

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [1]:
%timeit [i**2 for i in range(1,15)]

857 ns ± 5.79 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [2]:
import numpy as np
%timeit np.arange(1,15)**2

1.24 µs ± 22.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
a = np.array([
    [7,3], [2,5], [3,5]
])
a.ndim

2

In [6]:
b = np.array([[[]]])
b.ndim

3

In [10]:
c = [
    [5,8,9,'nashit']
]

In [12]:
#2 dim
c[0][1]

8

In [33]:
d = [[[[7, 8, 9], ['a', 'b', 'c']]]]

In [34]:
#4 dim
d[0][0][1][0]

'a'

In [36]:
e = np.array([[[[5,7,8]]]])
e.ndim

4

In [42]:
f = np.array([8,3,5], ndmin = 7 )
f

array([[[[[[[8, 3, 5]]]]]]])

In [43]:
f.ndim

7

In [47]:
g = np.arange(3,3)
g
g.ndim

1

In [50]:
h = np.zeros((6,4))
h

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
i = np.ones((3,3))
i

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
j = np.eye(5)
j

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
k = np.eye(4, 6)
print(k)
k.ndim

2

In [59]:
l = np.random.rand(3,4)
l

array([[0.88516878, 0.38034326, 0.90293961, 0.57966898],
       [0.47213206, 0.86662551, 0.45617375, 0.62931541],
       [0.19196953, 0.55813934, 0.02176424, 0.07667066]])

In [73]:
a = [[[np.random.randint(2,5)]]]
b = np.array(a)
b.ndim

3

In [12]:
import numpy
a = numpy.array([[6,3,2,9]])
#                 1,2,3,4
print(a)
print()
print(a.shape)
print()
b = numpy.array([5,2,7,8,9,0,1])
print(b)
print()
print(b.shape)

[[6 3 2 9]]

(1, 4)

[5 2 7 8 9 0 1]

(7,)


In [7]:
c = numpy.array([[[5,2,6,8,9,0]]])
c.shape

(1, 1, 6)

In [86]:
a = np.array([3,5,7,1,6,4,1,2,2])
print(a.ndim)
# dimensions 2d(x*y), 3d(x*y*z)
b = a.reshape(3,3)
print(b)
print(b.ndim)

1
[[3 5 7]
 [1 6 4]
 [1 2 2]]
2


In [88]:
a = np.array([3,5,7,1,6,4,1,2,2,4,2,8])
print("original dimensions:" ,a.ndim)
b = a.reshape(2,3,2)
print(b)
print("reshaped dimensions: ", b.ndim)

original dimensions: 1
[[[3 5]
  [7 1]
  [6 4]]

 [[1 2]
  [2 4]
  [2 8]]]
reshaped dimensions:  3


In [21]:
d = numpy.array([[3,7,7],[7,9,7]])
d.shape
#d.ndim

(2, 3)

In [22]:
e = numpy.array([
    [[2,5,9],[5,8,9],[7,0,2],[5,4,9]]
])

In [23]:
e.shape

(1, 4, 3)

In [24]:
e.ndim

3

In [25]:
f = numpy.array([3,7,9,2,4])
#                0,1,2,3,4
#               -5, -4, -3, -2, -1
f[1]

7

In [26]:
f[-2]

2

In [30]:
g = numpy.array([
    [7, 3, 8], 
    [6, 2, 9]
])

g[1,2]

9

In [31]:
g[-2,-3]

7

In [34]:
h = numpy.array([
    [
        [8,3,5],
        [7,2,4]]
])
h.shape

(1, 2, 3)

In [35]:
h[0]

array([[8, 3, 5],
       [7, 2, 4]])

In [40]:
h[0, 1, 2]

4

In [42]:
a = numpy.array([4, 2, 6,3])
b = numpy.array([8,3,4, 6])
#1/4 =0.25 =0; 2/3 = 0.66 = 0; 6/4= 1; 
# 4/8 = .5, 2/3 = .66, 6/4 = 1.5, 3/6 = ,.5
# -4, -1, 2, -3
a+b

array([12,  5, 10,  9])

In [43]:
numpy.add(a,b)

array([12,  5, 10,  9])

In [45]:
c = numpy.array([[4, 3, 6, 2], [4, 2, 5, 7]])
d = numpy.array([[1, 5, 2, 9], [3, 0, 3, 2]])
c+d

array([[ 5,  8,  8, 11],
       [ 7,  2,  8,  9]])

In [46]:
a-b

array([-4, -1,  2, -3])

In [47]:
numpy.subtract(a,b)

array([-4, -1,  2, -3])

In [48]:
b-a

array([ 4,  1, -2,  3])

In [49]:
numpy.subtract(b,a)

array([ 4,  1, -2,  3])

In [50]:
a*b

array([32,  6, 24, 18])

In [51]:
c*d

array([[ 4, 15, 12, 18],
       [12,  0, 15, 14]])

In [52]:
numpy.multiply(a,b)

array([32,  6, 24, 18])

In [53]:
a/b

array([0.5       , 0.66666667, 1.5       , 0.5       ])

In [54]:
numpy.divide(a,b)

array([0.5       , 0.66666667, 1.5       , 0.5       ])

In [55]:
numpy.mod(a,b)

array([4, 2, 2, 3])

In [56]:
a%b

array([4, 2, 2, 3])

In [58]:
numpy.reciprocal(a)

array([0, 0, 0, 0])

In [59]:
#statistical methods
numpy.min(a)

2

In [60]:
d = numpy.array([1,2,3,4])
# 1/1 = 1; 1/2 = 0.5= 0; 1/3 = 0; 0.24 n= 0
numpy.reciprocal(d)

array([1, 0, 0, 0])

In [66]:
e = numpy.array([0.25, 0.7, 0.33, 123])
1/e

array([4.        , 1.42857143, 3.03030303, 0.00813008])

In [67]:
numpy.reciprocal(e)

array([4.        , 1.42857143, 3.03030303, 0.00813008])

In [68]:
a

array([4, 2, 6, 3])

In [74]:
print(numpy.max(a))
print(numpy.argmax(a)) #index position

6
2


In [70]:
numpy.sqrt(a)

array([2.        , 1.41421356, 2.44948974, 1.73205081])

In [71]:
numpy.sin(a)

array([-0.7568025 ,  0.90929743, -0.2794155 ,  0.14112001])

In [72]:
numpy.cos(a)

array([-0.65364362, -0.41614684,  0.96017029, -0.9899925 ])

In [75]:
print(numpy.min(a))
print(numpy.argmin(a))

2
1


In [77]:
#Location of the minimum
b = numpy.array([9, 3, 1, 4, 5, 6, 3, 7, -1])
numpy.argmin(b)

8

In [80]:

print("org narray: ", a)
print()
print("processed array: ", numpy.cumsum(a))

org narray:  [4 2 6 3]

processed array:  [ 4  6 12 15]


In [81]:
#Cumulative sum of the array: the elements are added to the previous element
numpy.cumsum(b)

array([ 9, 12, 13, 17, 22, 28, 31, 38, 37])

In [2]:
import numpy
a = numpy.array([4, 2, 6,3])
a.itemsize

4

In [3]:
a.size

4

In [4]:
a.nbytes

16

In [5]:
import numpy

b = numpy.array([54,32,45,67])
b.nbytes

16

In [7]:
c = numpy.array([[3, 5],[4, 1]])
c.nbytes

16

In [9]:
b = numpy.array([54,32,45,67])
b.ndim

1

In [10]:
d = b.reshape(2,2)
d

array([[54, 32],
       [45, 67]])

In [11]:
d.ndim

2

In [28]:
e = numpy.array([6, 1, 2, 3, 4,5 ,6 ,7])
f = e.reshape(1,4,2)

In [29]:
f

array([[[6, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [27]:
f.ndim

3

In [30]:
g = numpy.array([3, 5, 7, 8, 9, 3])

In [31]:
h=g.reshape(2,3)
h

array([[3, 5, 7],
       [8, 9, 3]])

In [32]:
h.ndim

2

In [33]:
g.reshape(1,2,3)

array([[[3, 5, 7],
        [8, 9, 3]]])

In [35]:
h=g.reshape(2,1,3)
h

array([[[3, 5, 7]],

       [[8, 9, 3]]])

In [36]:
h.ndim

3

In [39]:
h[1,0]

array([8, 9, 3])

In [5]:
#Broadcasting
#Either both can have similar shape or either need to have a single element/shape
import numpy as np
a = np.array([4, 2, 5, 1]) # shape(4,)
b = np.array([5]) # shape(1,)
a+b

array([ 9,  7, 10,  6])

In [6]:
# Broadcast error -> dimension same + similar shape/shape

In [8]:

a = np.array([[1,2], [3,2]])
print(a.shape)
b = np.array([[1,4,3], [3,2]])
print(b.shape)
#a+b

(2, 2)
(2,)


C:\Users\s_nas\AppData\Local\Temp\ipykernel_8128\832421211.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([[1,4,3], [3,2]])


In [12]:
a = np.array([[2,3], [4,2]])
b = np.array([[1, 3, 4], [3,2,5]])
print(b.shape)
a.shape

(2, 3)


(2, 2)

In [10]:
b = np.array([[1,3,4], [3,2,5]])
print(b.shape)

(2, 3)


In [14]:
#Different shapes & a non-single shaped array creates the broadcast error
a*b


ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 